### ISSUE TITLE
Which version of GlobalBioIm and ASPIRE should I choose?

### ISSUE THREAD

**Issue by TheRealPoseidon** [Biomedical-Imaging-Group/CryoEM-Joint-Refinement#1]
Hi Mona! I read your paper and found this repo. Thank you.

When I'm running the 'main.m' in '\experiments' an error occur.(at expand_vol_KBWF (line 45))
Array indices must be positive integers or logical values.
expand_vol_KBWF (line 45)
c = ADMM.OutOp.evolxopt{end};

I'm wondering if I install the wrong GlobalBioIm. Could you help me out.

**Comment by TheRealPoseidon** [comment]
> Hi Mona! I read your paper and found this repo. Thank you.
> 
> When I'm running the 'main.m' in '\experiments' an error occur.(at expand_vol_KBWF (line 45)) Array indices must be positive integers or logical values. expand_vol_KBWF (line 45) c = ADMM.OutOp.evolxopt{end};
> 
> I'm wondering if I install the wrong GlobalBioIm. Could you help me out.

Before this error

Expansion on KBWF...
---> Start Opti ADMM ... 
Iter:     1
Iter:    50
Iter:   100
Iter:   150
Iter:   200
Maximum number of iterations reached: 200
... Optimization finished 
Elapsed time (s): 2.52e+00 (200 iterations).

**Comment by esoubies** [comment]
Hello,
Indeed, there was few lines related to the display in optimization algorithms which were not adapted to the lastest version of GlobalBioIm. I pushed the modifications. Now it should work with the lastest GlobalBioIm and the lastest ASPIRE.

I let Mona double check my modifications. In particular I had to do a small hack in the apply of LinOpPBTShift in order to force the copy of the input before giving it to the mex function. Otherwise the input was modified by the mex an its size was exploding... Don't really know why, have you already seen that ?

Best,
Emmanuel

**Comment by TheRealPoseidon** [comment]
> Hello, Indeed, there was few lines related to the display in optimization algorithms which were not adapted to the lastest version of GlobalBioIm. I pushed the modifications. Now it should work with the lastest GlobalBioIm and the lastest ASPIRE.
> 
> I let Mona double check my modifications. In particular I had to do a small hack in the apply of LinOpPBTShift in order to force the copy of the input before giving it to the mex function. Otherwise the input was modified by the mex an its size was exploding... Don't really know why, have you already seen that ?
> 
> Best, Emmanuel

 Hello Prof Emmanuel
Haven't seen this exploding problem yet, still stuck at expand_vol_KBWF.m line 45 before you upload new modifications. lol
Thank you.
Another question is that I'm using a computer with windows system. Neither '.mexa64' nor '.mexmaci64' can work on windows.
Could you upload c files for mex?

**Comment by MonaZI** [comment]
Hi,

The version of the GlobalBioIm library I used was 1.0.1 (https://github.com/Biomedical-Imaging-Group/GlobalBioIm/releases/tag/v1.0.1). Please check this version. For ASPIRE, you can use the latest version.

In case you want to use the latest version of the GlobalBioIm library, in `./functions/expand_vol_KBWF.m`, to get the final result after running ADMM, you need to get `xopt` rather than `OutOp.evolxopt{end}` from the ADMM object. This means you need to change line 45, `c = ADMM.OutOp.evolxopt{end};` to `c = ADMM.xopt;`.

If you choose to use the latest version, you might run into other similar errors when running the code, as there are some small differences between the class attributes in the two versions. Finally, regarding the mex files, I will update the repo soon to address the issue of running the mex files on different operating systems.

**Comment by MonaZI** [comment]
Hi, the source mex files are added to `./LinOpCryo/src/` folder. Please also check ReadMe for some brief compilation instructions. The code currently works with the latest version of GlobalBioIm library.
